# Generated by Django 5.2.6 on 2025-10-18 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('l', 'litre'), ('kg', 'kilogram'), ('m2', 'm²'), ('pcs', 'piece'), ('pack', 'pack')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
