# Generated by Django 5.2.6 on 2025-11-19 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_category_code_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(default='item', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.material')),
            ],
        ),
    ]
