# Generated by Django 5.2.6 on 2025-12-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_basket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='status',
            field=models.CharField(choices=[('A', 'Added'), ('B', 'Bought')], default='A'),
        ),
    ]
