# Generated by Django 5.2.6 on 2026-01-05 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_basket_count_alter_book_year'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='basket',
            unique_together={('user', 'material')},
        ),
    ]
